default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOSTNAME'] %>
  port: <%= ENV['DB_PORT'] %>
  pool: <%= ENV['DB_POOL'] %>

production:
  <<: *default

release:
  <<: *default

staging:
  <<: *default

development:
  <<: *default
  database: proficiency_development
  username:
  password:

test:
  <<: *default
  database: proficiency_test
  pool: 5
  username:
  password:
